<?php // 
	echo "<table style = 'width: 620px; height: 296px; background-color: #D0F5A9'>";
		echo "<tr valign = 'middle' style = 'height: 10px'><div align = 'center' valign = 'middle' style = 'width: 620px; height: 5px; background-color: #D0F5A9; padding-top: 5px'><font face = 'Calibri' size = '2' color = grey>FEBRUARY 2013</font></div></tr>";
		echo "<tr>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Sun</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Mon</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Tues</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Wed</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Thurs</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Fri</font></td>";
			echo "<td align = 'center' style = 'background-color: white; border: solid 1px #ffffff; width: 88px; height: 20px'><font face = 'Calibri' size = '3' color = grey>Sat</font></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>1</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>2</font></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>3</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>4</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>5</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>6</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>7</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>8</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>9</font></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>10</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>11</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>12</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>13</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>14</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>15</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>16</font></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>17</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>18</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>19</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>20</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>21</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>22</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>23</font></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>24</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>25</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>26</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'>27</font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
			echo "<td align = 'right' valign = 'top' style = 'height: 46px; background-color: white; border: solid 1px #ffffff'><font face = 'Calibri' size = '2' color = 'grey'></font></td>";
		echo "</tr>";
	echo "</table>";
?>