<?php /* Event Thumbnail - The following are still treated as test elements generated by the browser on the client-side - Information contained in the following elements will have to be replaced by dummy data by the end of February */ ?>

<a href = 'Profile_EventPage.php'>
<div align = 'center' valign = 'middle' style = 'width: 292px; height: 85px; background-color: #FFFFFF; border: solid 1px #FFFFFF; border-radius: 5px; box-shadow: 0px 0px 4px 0px #86B404'>
<table align = 'left' valign = 'middle' style = 'width: 286px; margin-top: 1px; margin-left: 3px'>
	<td align = 'center' valign = 'middle' style = 'width: 70px'>
    <img src = '/LyfSync/DP.jpg' style = 'height: 74px'>
   	</td>
	<td align = 'left' valign = 'middle' style = 'width: 200px; padding-left: 4px'>
	<font face = 'Calibri' size = '3' color = '#2E2E2E'>Event Name</font>
		<table style = ' width: 197px; border-top: solid 1px #E6E6E6'>
			<tr>
            	<td valign = 'middle' style = 'width: 10px'><img src = '/LyfSync/ArrowSmall.jpg' style = 'height: 8px'>
                </td>
                <td align = 'left' valign = 'top'><font face = 'Calibri' size = '2' color = 'Grey'>'Tagline'</font>
                </td>
            </tr>
			<tr>
            	<td valign = 'middle' style = 'width: 10px'><img src = '/LyfSync/ArrowSmall.jpg' style = 'height: 8px'>
                </td>
                <td align = 'left' valign = 'top'><font face = 'Calibri' size = '2' color = 'Grey'>Date & Time</font>
                </td>
            </tr>
			<tr>
            	<td valign = 'middle' style = 'width: 10px'><img src = '/LyfSync/ArrowSmall.jpg' style = 'height: 8px'>
                </td>
                <td  align = 'left' valign = 'top'>
                <font face = 'Calibri' size = '2' color = 'Grey'>Location</font>
                </td>
				<td align = 'right'>
                <font face = 'Calibri' size = '2' color = 'Grey'>Free</font>
                </td>
            </tr>
        </table>
	</td>
</table>

</div>
</a>
